### ISSUE TITLE
Integrate Discord bot that can answer questions based on documentation

### ISSUE THREAD

**Issue by generall** [qdrant/qa-automation#1]

**Comment by varshith257** [comment]
/attempt #1 
@generall Can get more context of the issue? I will be happy if you provide so :)

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | 8 bounties from 4 projects | <div align="center">TypeScript, Go</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clzvfkcdg0002mb09x1q0xpbk/cancel-attempt) |

**Comment by Ya-shh** [comment]
/attempt #1

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clzvfkcdg0002mb09x1q0xpbk/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by generall** [comment]
Issue dedicated for @Ya-shh , sorry for the noise
